[bar.default]
background_opacity = 0.0
capsule = true
capsule_padding = 12.0
capsule_radius = 0
capsule_thickness = 0.8
center = ["clock"]
end = [
    "weather",
    "ram",
    "tray",
    "bar",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session",
]
font_scale = 1.1
layer = "top"
margin_ends = 200
start = ["launcher", "wallpaper", "workspaces", "cat", "media"]
thickness = 32
widget_spacing = 12

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 25

[brightness]
minimum_brightness = 0.05

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 420

[location]
address = "Kraków"

[nightlight]
enabled = false
temperature_night = 2600

[notification]
background_opacity = 0.75
position = "top_center"

[plugins]
enabled = ["noctalia/bongocat", "noctalia/screen_recorder"]

[shell]
clipboard_enabled = false
corner_radius_scale = 0.0
font_family = "Iosevka NFM"
lang = "en"
polkit_agent = true

[shell.animation]
speed = 2.0

[shell.panel]
control_center_placement = "floating"
transparency_mode = "glass"
wallpaper_placement = "floating"

[shell.screen_corners]
enabled = true

[shell.screenshot]
annotate = true
copy_to_clipboard = true
directory = "~/Pictures/Screenshots"
freeze_screen = true
pipe_command = ""
pipe_to_command = true
remember_last_region = false
save_to_file = true
show_cursor = false

[theme]
builtin = "Rosé Pine"
community_palette = "Gruber Darker"
mode = "dark"
source = "builtin"
wallpaper_scheme = "faithful"

[theme.templates]
builtin_ids = ["btop", "ghostty", "gtk3", "gtk4", "hyprland", "qt", "starship"]
community_ids = [
    "claude-code",
    "spicetify",
    "brave",
    "discord",
    "libreoffice",
    "obsidian",
    "heroiclauncher",
    "prismlauncher",
    "steam",
    "fastfetch",
    "obs",
    "papirus-icons",
    "lazygit",
    "tmux",
]
enable_builtin_templates = true

[wallpaper]
directory = "/home/stshalson/Pictures/Wallpapers"
transition = ["stripes"]

[weather]
effects = false

[widget.cat]
type = "noctalia/bongocat:cat"
